### ISSUE TITLE
Allow `down` migrations

### ISSUE THREAD

**Issue by acaloiaro** [acaloiaro/neoq#77]
Currently `up` migrations are run when neoq starts. In order to roll back to previous releases, users need to be able to "roll back" their `neoq_jobs` schema to previous versions. 

Currently, there is no way to specify which schema version the the current version of neoq should use.

**Comment by elliotcourant** [comment]
Since you're embedding the migrations at build time, you could determine what the "latest" migration version is based on the files in that embed. If the version in the DB is greater than that you could start with raising a log message at the very least. But for an older version to know how to downgrade from a migration it doesn't have might be tricky.

**Comment by acaloiaro** [comment]
I wonder if this issue can be addressed with a release policy that mandates 2-phase release for all migrations. 

1. The `down` migration is released 
2. Followed by the release containing the `up` migration

Obviously not perfect, but it allows the existing migration tooling to be used. Maybe it's a start of something.

**Comment by acaloiaro** [comment]
Closing since migrations change so infrquently
