### ISSUE TITLE
neoq_jobs.id is integer not bigint

### ISSUE THREAD

**Issue by justinclift** [acaloiaro/neoq#89]
Looking at the schema created by neoq for job submission, one worrying thing standing out is that the `neoq_jobs`.`id` column is an integer rather than bigint.

Shouldn't this be a bigint, as it's fairly likely some people will otherwise hit the maximum integer size (2,147,483,647) when using neoq?

**Comment by acaloiaro** [comment]
Good catch -- it should be big int.

**Comment by justinclift** [comment]
It also doesn't seem to have a unique constraint on the `neoq_jobs`.`id` column, but I'm not (yet) sure if that's on purpose or not.

Discovered that when making the `neoq_jobs`.`id` a foreign key (for referential integrity lookup) when cobbling together an initial "job responses" table.

**Comment by acaloiaro** [comment]
That was deliberate to reduce the number of indices. The `neoq_jobs` table is intended to be implementation detail rather than something that one delves into and integrates tightly with one's system. 

As a result, there is no unique constraint on `neoq_jobs.id` to reduce the number of indices, increasing insertion performance. 
 
With that said, it is a postgres table after all, so users interacting with it is no surprise, and I wouldn't say there's anything wrong with inspecting it directly. 

What I would caution against, however, is assuming that its schema is static, at least until neoq hits `1.0` (which will be next month, as the current plan goes). Even then, every _major version change_ may migrate the table schema. So I'll still caution against becoming dependent on its schema.

**Comment by justinclift** [comment]
Thanks.  I'm just doing tentative exploring of potential RabbitMQ alternatives, and am aware Neoq is in the early stages. :smile:

**Comment by acaloiaro** [comment]
Sounds good. Feel free to keep opening issues for anything you find unexpected or interesting. It's always good to get feedback on what's unexpected or potential bugs. 

I'll migrate the `id` field to `bigint` in the next release.

**Comment by acaloiaro** [comment]
@justinclift Release `0.37.0` is available with this fix. Thanks for the report!

**Comment by justinclift** [comment]
No worries, you're welcome. :smile:
